### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by omalleh** [SitanHuang/HVACTroubleshoot#1]
I am interested in what you have developed.
Can you give me a further description of the required inputs?
Could you provide me a use case and example for the software?

**Comment by SitanHuang** [comment]
I forgot most of the details about this project and haven't used it for long. Here's all I know: I used HVAC data from our company, including the fixes we've done to solve the problems. The app trains a neural net that allows to suggest a fix based on the data provided.

**Comment by omalleh** [comment]
Thank you for the insight, most appreciated.
